---
- name: "aws でshowコマンドのテスト"
  hosts: "{{ vsrx_host }}"
  gather_facts: false
  tasks:
    - name: "{{ private_cmd_1 }} の確認"
      junos_command:
        commands: "{{ private_cmd_1 }}"
      register: results

    - name: "show version 結果表示"
      debug:
        msg: "{{ results.stdout_lines[0] }}"

    - name: "show configration"
      junos_command:
        commands: "{{ private_cmd_2 }}"
      register: results2

    - name: "show configration 結果表示"
      debug:
        msg: "{{ results2.stdout_lines[0] }}"

    - name: "show chassis hardware"
      junos_command:
        commands: "{{ private_cmd_3 }}"
      register: results3

    - name: "show chassis hardware 結果表示"
      debug:
        msg: "{{ results3.stdout_lines[0] }}"
