---
- name: "awx でshowコマンドのテスト"
  hosts: "{{ vsrx_host }}"
  gather_facts: false
  tasks:
    - name: "{{ private_cmd_1 }} 確認"
      junos_command:
        commands: "{{ private_cmd_1 }} | {{ grep_para }}"
      register: results

    - name: "{{ private_cmd_1 }}  結果表示"
      debug:
        msg: "{{ results.stdout_lines[0] }}"

    - name: "{{ private_cmd_2 }} 確認"
      junos_command:
        commands: "{{ private_cmd_2 }}"
      register: results2

    - name: "{{ private_cmd_2 }} 結果表示"
      debug:
        msg: "{{ results2.stdout_lines[0] }}"

    - name: "{{ private_cmd_3 }} 確認"
      junos_command:
        commands: "{{ private_cmd_3 }}"
      register: results3

    - name: "{{ private_cmd_3 }} 結果表示"
      debug:
        msg: "{{ results3.stdout_lines[0] }}"
